name: barber_booking
description: "A SaaS-style barber booking Flutter app"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.13.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  bloc:
  equatable:
  flutter_bloc:
  firebase_core:
  firebase_auth:
  cloud_firestore:
  go_router:
  flutter_localizations:
    sdk: flutter
  intl:
  shared_preferences:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
  uses-material-design: true
  generate: true
