// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.macOS:
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for this platform.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-2NQ0ce2UgdWVgOnT2d8KbsQRaejFETw',
    appId: '1:974724910275:web:4ece0c6781810565db2676',
    messagingSenderId: '974724910275',
    projectId: 'flash-392b3',
    authDomain: 'flash-392b3.firebaseapp.com',
    storageBucket: 'flash-392b3.appspot.com',
    measurementId: 'G-B7CQ47WTMQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASgSN_XNyOaNqSzpuZP1sFaXA8ba-jsAY',
    appId: '1:974724910275:android:52921993a5ec6d18db2676',
    messagingSenderId: '974724910275',
    projectId: 'flash-392b3',
    storageBucket: 'flash-392b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnmnBsSj1DMGTazAfNd6ErriLuOAhiOc',
    appId: '1:974724910275:ios:fe4f625bbfa10ea9db2676',
    messagingSenderId: '974724910275',
    projectId: 'flash-392b3',
    storageBucket: 'flash-392b3.appspot.com',
    iosBundleId: 'com.example.barberBooking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-2NQ0ce2UgdWVgOnT2d8KbsQRaejFETw',
    appId: '1:974724910275:web:6dc7853aa32c0064db2676',
    messagingSenderId: '974724910275',
    projectId: 'flash-392b3',
    authDomain: 'flash-392b3.firebaseapp.com',
    storageBucket: 'flash-392b3.appspot.com',
    measurementId: 'G-4K8YJ4NCKL',
  );
}
